## [Evaluamos al profesor Marco Cañas Aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUREJPV1kxUk1JV1ozTFJIQVNIQjY5WEY3US4u)

# [Vínculo al formulario de google del diagnóstico y de la prueba final](https://forms.gle/LXCJMWhBQjfHGEXu8)

# Empezamos tomando los nombres de los estudiantes de la lista de Isnelia

In [23]:
import os 
import pandas as pd 

df_isne = pd.read_excel(r"C:\Users\marco\Documentos\extension\camino-udea\9_asistencia_evaluacion\pivu_caucasia.xlsx", sheet_name='Inscritos', header=2) 
df_isne.head()

,#,NOMBRES Y APELLIDOS,TIPO DE DOCUMENTO,DOCUMENTO,TEL. FIJO,TELÉFONOS,CORREO,FIRMA,Unnamed: 8
0,1,Albeiro Andrés Ruiz Velasquez,Tarjeta de identidad,1038110235,3206679796,3206679796,albeiro123ruiz@gmail.com,NaN,NaN
1,2,Alisson A. Hoyos,Cédula,1038117202,3225678440,3225678440,cazul8028@gmail.com,NaN,NaN
2,3,Ana Sofia Ramos Espinosa,Tarjeta de identidad,1041633525,3117919507,3232986579,anasofiaespinosa55@gmail.com,NaN,NaN
3,4,Andrés De Jesús Baldovino Mangones,Cédula,1038648794,3107585880,3107585880,andresbaldovino893@gmail.com,NaN,NaN
4,5,Blarney Molina Quintana,Tarjeta de identidad,1040505284,3225647288,3225647288,blarneymolina8@gmail.com,NaN,1

# Ver la lista de nombre en el orden de la lista de Isnelia

In [24]:
df_isne['NOMBRES Y APELLIDOS'].values

<StringArray>
[    'Albeiro Andrés  Ruiz Velasquez ',                    'Alisson A. Hoyos',
            'Ana Sofia Ramos Espinosa', 'Andrés De Jesús  Baldovino Mangones',
             'Blarney Molina Quintana',             'Camila  Campo Gutiérrez',
                     'Hannah Restrepo',               'Isabela Arrieta Hoyos',
           'Isabella  Casarrubia Mora',                'Jhon Mario Rúa Pérez',
      'José Mauricio Herrera Artehaga',       'Juan José  Severiche Sánchez ',
         'Juan José Zapata Villarreal',        'Luis Fernando  Mendoza Villa',
         'Luz Adriana Montaño Herrera',     'María Alejandra  Cuesta Cladera',
              'María Isabel  Beltrán ',          'María Luisa  Díaz Londoño ',
             'Mariana  Esquivel Llano',          'Paola Andrea  Soto Montes ',
               'Rafael Villera Donado',          'Salomé  Torregrosa Medrano',
      'Samuel Andrés Peralta Herrera ',          'Samuel Isaac Camargo López',
             'Santiago Martínez Conde',             'Sara Flórez Villanueva ',
                'Sara Paola Polo Mass',      'Sarakarin  Contreras Martínez ',
          'Taliana Andrea Ruiz Urango',                       'Taliana Menco',
              'Tania  Restrepo Prasca',           'Thamara Ormeno De La Rosa',
          'Valeria Mendoza Torregroza',               'Valeria Prada Garnica',
   'Yenifer Taliana Aguirre Carvajal ']
Length: 35, dtype: str

# Tomar los resultados obtenidos de la prueba final

In [25]:
import pandas as pd 

df_marco_final = pd.read_excel(r"C:\Users\marco\Documentos\extension\camino-udea\9_asistencia_evaluacion\prueba_final_pivu_caucasia_excel.xlsx") 
df_marco_final

,NOMBRES Y APELLIDOS,Pregunta 41,Pregunta 42,Pregunta 43\n,Pregunta 44,Pregunta 45,Pregunta 46,Pregunta 47,Pregunta 48,Pregunta 49,...,Pregunta 69,Pregunta 70,Pregunta 71,Pregunta 72,Pregunta 73,Pregunta 74,Pregunta 75\n,Pregunta 76\n,Pregunta 77\n,Pregunta 78\n
0,Samuel Andrés Peralta Herrera,C,B,B,C,B,A,B,B,C,...,A,B,C,D,B,C,A,B,D,D
1,Albeiro Andres Ruiz Velasquez,C,D,B,C,B,A,B,B,C,...,A,B,C,D,B,C,A,B,D,D
2,Tania restrepo prasca,C,D,B,C,B,A,B,B,C,...,A,B,C,D,B,C,A,B,D,C
3,Paola Andrea Soto Montes,B,A,C,D,C,A,B,D,D,...,D,D,D,C,C,B,D,C,A,D
4,Thamara Ormeno,B,A,C,D,C,A,B,D,D,...,D,D,D,C,C,B,A,C,A,D
5,Salome Torregrosa medrano,B,A,C,D,C,A,B,D,D,...,D,D,D,C,C,D,C,A,A,D
6,Hannah restrepo,C,D,B,C,B,A,B,B,C,...,A,B,C,D,B,C,A,B,D,C
7,Maria Luisa Diaz Londoño,C,B,C,D,B,A,D,D,D,...,D,B,C,C,B,C,A,B,A,C
8,Valeria Mendoza Torregroza,A,C,C,D,C,A,C,B,A,...,D,B,C,A,B,C,D,C,B,C
9,José Mauricio Herrera Artehaga,C,C,C,D,C,B,B,D,A,...,A,D,B,C,B,B,A,C,C,A
10,Isabela Arrieta,C,D,C,D,D,D,C,D,B,...,D,B,C,C,B,C,A,A,A,A
11,Sara Flórez Villanueva,B,C,C,D,C,D,B,D,D,...,C,D,C,A,A,C,A,D,B,C
12,María Isabel Beltrán,C,B,A,B,C,B,A,D,D,...,A,A,C,B,C,C,B,C,D,D
13,Rafael Villera Donado,B,C,A,D,C,A,B,A,B,...,D,B,C,C,B,C,A,A,D,C
14,Santiago Martinez Conde,B,B,C,A,C,B,C,D,D,...,D,B,B,C,A,C,A,D,B,C
15,Taliana Ruiz,C,C,C,D,C,B,B,D,B,...,D,B,C,C,A,A,C,D,B,C
16,LUIS FERNANDO MENDOZA VILLA,B,C,C,D,D,D,A,A,A,...,A,A,A,B,B,B,A,A,D,C
17,Mariana Esquivel Llano,B,C,C,D,C,B,D,D,C,...,B,D,A,A,A,B,C,B,D,A
18,Juan José Zapata Villarreal,C,C,C,D,B,C,C,A,B,...,D,B,C,A,A,C,B,D,D,C
19,Blarney Molina,C,C,C,D,C,B,B,D,A,...,C,D,A,C,A,A,C,B,B,A
20,Andrés De Jesús Baldovino Mangones,C,A,C,A,C,A,B,B,A,...,C,A,C,D,B,A,A,B,D,A
21,Alisson Azul Hoyos Vega,C,D,C,D,C,B,D,A,B,...,A,B,C,D,B,C,A,D,B,C

In [26]:
df_marco_final['NOMBRES Y APELLIDOS']

0         Samuel Andrés Peralta Herrera
1         Albeiro Andres Ruiz Velasquez
2                 Tania restrepo prasca
3              Paola Andrea Soto Montes
4                        Thamara Ormeno
5              Salome Torregrosa medrano
6                        Hannah restrepo
7              Maria Luisa Diaz Londoño
8            Valeria Mendoza Torregroza
9        José Mauricio Herrera Artehaga
10                      Isabela Arrieta
11               Sara Flórez Villanueva
12                 María Isabel Beltrán
13                Rafael Villera Donado
14              Santiago Martinez Conde
15                          Taliana Ruiz
16          LUIS FERNANDO MENDOZA VILLA
17               Mariana Esquivel Llano
18          Juan José Zapata Villarreal
19                       Blarney Molina
20    Andrés De Jesús Baldovino Mangones
21              Alisson Azul Hoyos Vega
Name: NOMBRES Y APELLIDOS, dtype: str

# Ordenar los resultados de acuerdo al orden de los nombres de los estudiantes que tiene Isnelia

In [28]:
import pandas as pd

# 1. Realizamos el merge 'right' para asegurar que todos los nombres de df_isne estén presentes
df_marco_final = pd.merge(
    df_marco_final, 
    df_isne[['NOMBRES Y APELLIDOS']], 
    on='NOMBRES Y APELLIDOS', 
    how='right'
)

# 2. SOLUCIÓN AL ERROR: 
# Si hay nombres duplicados en el diagnóstico, nos quedamos solo con el primero 
# antes de intentar reordenar.
df_marco_final = df_marco_final.drop_duplicates(subset=['NOMBRES Y APELLIDOS'], keep='first')

# 3. Reordenamiento seguro
# CORRECCIÓN: Filtramos los valores nulos (dropna) y eliminamos duplicados (unique) de la lista maestra
orden_maestro = df_isne['NOMBRES Y APELLIDOS'].dropna().unique().tolist()

# Aplicamos la categorización usando la lista limpia
df_marco_final['NOMBRES Y APELLIDOS'] = pd.Categorical(
    df_marco_final['NOMBRES Y APELLIDOS'], 
    categories=orden_maestro, 
    ordered=True
)

# Ordenamos y reseteamos el índice
df_marco_final = df_marco_final.sort_values('NOMBRES Y APELLIDOS').reset_index(drop=True)

# Convertimos la columna de nuevo a texto normal (opcional)
df_marco_final['NOMBRES Y APELLIDOS'] = df_marco_final['NOMBRES Y APELLIDOS'].astype(str)

print("Se ordenaron los resultados de acuerdo al orden de los estudiantes de Isnelia.")

Se ordenaron los resultados de acuerdo al orden de los estudiantes de Isnelia.

In [29]:
from thefuzz import process
porcentaje_coincidencia = 100   
# 1. Aseguramos limpieza básica primero
nombres_maestros = df_marco_final['NOMBRES Y APELLIDOS'].dropna().unique()

# 2. Función que retorna el puntaje para poder filtrar
def obtener_puntaje_coincidencia(nombre, lista_maestra):
    if pd.isna(nombre):
        return 0
    # process.extractOne devuelve (nombre_encontrado, puntaje)
    _, puntaje = process.extractOne(nombre, lista_maestra)
    return puntaje

# 3. Creamos una columna temporal de puntaje en el dataframe de diagnóstico
df_isne['puntaje_match'] = df_isne['NOMBRES Y APELLIDOS'].apply(
    lambda x: obtener_puntaje_coincidencia(x, nombres_maestros)
)

# 4. Filtramos los que tienen menos del 20% de coincidencia
estudiantes_sin_match = df_isne[df_isne['puntaje_match'] != porcentaje_coincidencia]

# 5. Obtenemos solo la lista de nombres
lista_nombres_criticos = estudiantes_sin_match['NOMBRES Y APELLIDOS'].tolist()

print(f"""Se encontraron {len(lista_nombres_criticos)} estudiantes con 
      coincidencia diferente a {porcentaje_coincidencia}%:""")
print(lista_nombres_criticos, len(lista_nombres_criticos))

Se encontraron 0 estudiantes con
      coincidencia diferente a 100%:
[] 0

In [30]:
df_isne['puntaje_match'].unique()

array([100])

In [ ]:
import numpy as np # C	C	C	D	C	B	C	D	D	B	C	A	D	B	B	B	C	C	C	C	C	C	D	A	B	D	D	A	D	B	C	C	A	C	A	D	B	C

lista_correctas_final = np.array([['C',	'C', 'C',	'D',	'C',	'B',	'C',	'D',	'D',	'B',	'C',	'A',	'D',\
    'B',	'B',	'B',	'C',	'C',	'C',	'C',	'C',	'C',	'D',	'A',	'B',	'D',\
        'D',	'A',	'D',	'B',	'C',	'C',	'A',	'C',	'A',	'D',	'B',	'C']])
lista_correctas_final

array([['C', 'A', 'A', 'A', 'A', 'B', 'C', 'A', 'A', 'A', 'C', 'D', 'B',
        'B', 'A', 'B', 'B', 'C', 'C', 'B', 'C', 'A', 'D', 'B', 'C', 'C',
        'D', 'A', 'A', 'B', 'C', 'B', 'B', 'C', 'B', 'A', 'B', 'B']],
      dtype='<U1')

In [ ]:
nombres_preguntas = ['Pregunta 41', 'Pregunta 42', 'Pregunta 43', 'Pregunta 44',
       'Pregunta 45', 'Pregunta 46', 'Pregunta 47', 'Pregunta 48',
       'Pregunta 49', 'Pregunta 50', 'Pregunta 51', 'Pregunta 52',
       'Pregunta 53', 'Pregunta 54', 'Pregunta 55', 'Pregunta 56',
       'Pregunta 57', 'Pregunta 58', 'Pregunta 59', 'Pregunta 60',
       'Pregunta 61', 'Pregunta 62', 'Pregunta 63', 'Pregunta 64',
       'Pregunta 65', 'Pregunta 66', 'Pregunta 67', 'Pregunta 68',
       'Pregunta 69', 'Pregunta 70', 'Pregunta 71', 'Pregunta 72',
       'Pregunta 73', 'Pregunta 74', 'Pregunta 75', 'Pregunta 76',
       'Pregunta 77', 'Pregunta 78']

In [ ]:
df_respuestas_correctas_final = pd.DataFrame(lista_correctas_final, \
    columns = nombres_preguntas)
df_respuestas_correctas_final

,Pregunta 41,Pregunta 42,Pregunta 43,Pregunta 44,Pregunta 45,Pregunta 46,Pregunta 47,Pregunta 48,Pregunta 49,Pregunta 50,...,Pregunta 69,Pregunta 70,Pregunta 71,Pregunta 72,Pregunta 73,Pregunta 74,Pregunta 75,Pregunta 76,Pregunta 77,Pregunta 78
0,C,A,A,A,A,B,C,A,A,A,...,A,B,C,B,B,C,B,A,B,B

In [ ]:
import pandas as pd

# 1. Limpieza básica de espacios (evita que "Juan " y "Juan" se vean como diferentes)
df_isne['NOMBRES Y APELLIDOS'] = df_isne['NOMBRES Y APELLIDOS'].str.strip()
df_marco_diagnostico['NOMBRES Y APELLIDOS'] = df_marco_diagnostico['NOMBRES Y APELLIDOS'].str.strip()

# 2. Eliminamos duplicados de la lista maestra para evitar el error de Reindex
# Es vital que la "llave" sea única
df_maestra_unica = df_isne[['NOMBRES Y APELLIDOS']].drop_duplicates(subset=['NOMBRES Y APELLIDOS'])

# 3. Realizamos el merge
# Usamos 'right' para que manden los nombres de la lista maestra
df_final = pd.merge(
    df_marco_diagnostico, 
    df_maestra_unica, 
    on='NOMBRES Y APELLIDOS', 
    how='right'
)

# 4. Solución al error de Reindex:
# Solo aplicamos reindex si nos aseguramos de que los índices son únicos
df_final = df_final.drop_duplicates(subset=['NOMBRES Y APELLIDOS'])
df_final = df_final.set_index('NOMBRES Y APELLIDOS').reindex(df_maestra_unica['NOMBRES Y APELLIDOS']).reset_index()

# 5. Verificación
print(f"Estudiantes únicos procesados: {len(df_final)}")

Estudiantes únicos procesados: 35

In [ ]:
df_marco_final

,Timestamp,Score,NOMBRES Y APELLIDOS,Pregunta 41,Pregunta 42,Pregunta 43\n,Pregunta 44,Pregunta 45,Pregunta 46,Pregunta 47,...,Pregunta 69,Pregunta 70,Pregunta 71,Pregunta 72,Pregunta 73,Pregunta 74,Pregunta 75\n,Pregunta 76\n,Pregunta 77\n,Pregunta 78\n
0,2026-04-06 18:53:34.340,0.0,Albeiro Andrés Ruiz Velasquez,B,A,C,C,D,B,A,...,C,A,C,A,C,A,C,C,D,B
1,2026-04-10 08:24:27.496,0.0,Alisson A. Hoyos,D,C,D,A,A,B,C,...,A,C,D,C,D,B,C,D,C,D
2,2026-04-06 19:11:55.583,0.0,Ana Sofia Ramos Espinosa,C,A,D,A,D,C,A,...,B,B,A,C,D,C,A,D,B,C
3,2026-04-10 11:02:30.753,0.0,Andrés De Jesús Baldovino Mangones,D,A,A,B,B,D,D,...,C,B,C,A,D,B,B,C,A,B
4,NaT,NaN,Blarney Molina Quintana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2026-04-06 19:12:01.790,0.0,Camila Campo Gutiérrez,D,A,C,B,A,C,B,...,B,C,A,B,D,C,A,B,B,A
6,2026-04-06 18:52:57.359,0.0,Hannah Restrepo,B,A,C,C,D,A,A,...,A,D,C,D,D,B,A,C,B,B
7,2026-04-10 13:27:38.280,0.0,Isabela Arrieta Hoyos,D,B,D,A,B,A,C,...,D,C,D,C,A,C,C,C,D,A
8,2026-04-06 18:56:25.033,0.0,Isabella Casarrubia Mora,D,B,A,A,B,C,C,...,A,B,C,A,B,B,C,A,B,C
9,2026-04-10 13:32:22.677,0.0,Jhon Mario Rúa Pérez,C,A,B,A,A,B,C,...,C,D,B,C,B,C,A,B,D,B
10,2026-04-06 19:16:24.929,0.0,José Mauricio Herrera Artehaga,C,C,C,B,A,B,C,...,A,B,C,B,D,A,B,A,C,B
11,2026-04-06 19:15:41.770,0.0,Juan José Severiche Sánchez,C,B,B,B,D,D,D,...,A,B,D,A,C,B,D,B,C,D
12,2026-04-06 19:20:24.740,0.0,Juan José Zapata Villarreal,D,C,A,A,C,B,C,...,B,D,D,A,D,C,A,A,B,D
13,2026-04-06 19:16:40.290,0.0,Luis Fernando Mendoza Villa,D,A,C,B,A,A,D,...,D,C,B,A,D,A,D,A,C,B
14,NaT,NaN,Luz Adriana Montaño Herrera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2026-04-06 19:14:01.218,0.0,María Alejandra Cuesta Cladera,C,C,B,A,B,C,D,...,C,D,C,B,A,B,C,B,C,C
16,2026-04-10 13:37:03.504,0.0,María Isabel Beltrán,C,A,B,B,D,B,B,...,B,A,C,C,A,B,B,B,B,B
17,2026-04-06 19:16:45.138,0.0,María Luisa Díaz Londoño,C,A,C,A,D,D,B,...,C,A,D,C,A,C,A,D,B,C
18,2026-04-06 19:02:33.665,0.0,Mariana Esquivel Llano,D,A,B,C,D,D,B,...,B,A,D,B,C,A,A,B,A,A
19,2026-04-10 13:47:13.970,0.0,Paola Andrea Soto Montes,C,A,A,A,A,C,B,...,C,A,B,D,A,C,C,D,B,B
20,2026-04-06 19:19:14.411,0.0,Rafael Villera Donado,C,B,D,A,D,A,B,...,B,B,A,C,B,A,C,B,A,C
21,2026-04-10 13:51:25.323,0.0,Salomé Torregrosa Medrano,C,A,C,A,A,C,B,...,C,B,A,C,A,B,C,D,B,B
22,2026-04-06 18:51:36.030,0.0,Samuel Andrés Peralta Herrera,C,A,A,B,A,C,D,...,B,A,A,A,B,B,D,B,A,C
23,2026-04-06 19:15:55.043,0.0,Samuel Isaac Camargo López,D,A,C,A,D,A,B,...,C,A,B,C,A,B,A,C,B,D
24,2026-04-10 14:00:38.223,0.0,Santiago Martínez Conde,C,A,B,B,D,D,C,...,B,C,D,C,D,C,C,B,C,C
25,2026-04-06 19:17:24.079,0.0,Sara Flórez Villanueva,D,A,B,B,B,D,C,...,D,B,C,D,D,D,C,C,A,A
26,NaT,NaN,Sara Paola Polo Mass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2026-04-06 19:07:46.812,0.0,Sarakarin Contreras Martínez,C,A,D,A,B,B,A,...,B,C,B,D,A,B,B,A,C,D
28,2026-04-10 14:06:54.240,0.0,Taliana Andrea Ruiz Urango,C,A,D,A,A,D,C,...,A,A,C,D,A,D,B,B,B,B
29,2026-04-06 18:53:52.918,0.0,Taliana Menco,D,C,C,B,A,D,C,...,C,A,C,B,D,A,B,C,D,D
30,NaT,NaN,Tania Restrepo Prasca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2026-04-06 19:14:59.581,0.0,Thamara Ormeno De La Rosa,D,A,A,A,D,A,C,...,A,B,B,A,C,A,B,B,A,C
32,2026-04-06 19:14:17.701,0.0,Valeria Mendoza Torregroza,C,C,C,C,C,C,D,...,B,A,B,C,A,C,C,B,C,C
33,2026-04-10 14:12:33.016,0.0,Valeria Prada Garnica,C,A,B,B,D,D,C,...,A,B,A,C,D,B,C,D,B,C
34,2026-04-06 19:18:38.724,0.0,Yenifer Taliana Aguirre Carvajal,C,D,B,A,D,D,C,...,A,C,B,A,D,B,C,B,A,B

In [ ]:
df_marco_final.to_excel(r"C:\Users\marco\Documentos\extension\camino-udea\9_asistencia_evaluacion\respuestas_prueba_final_limpia.xlsx",\
    index=False)